config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  
  resources :recipes, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = service.all_recipes
  end

  def show
    @recipe = service.find_recipe(params[:id])
  end

  private

  def service
    @service ||= ContentfulService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MsWebChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<table border='1'>
  <% @recipes.each do |recipe| %>
  <tr>
    <th>Title:</th>
    <td colspan="2"><%= recipe.title %></td>
  </tr>
  <tr>
    <th>Image:</th>
    <td><img src="<%= recipe.photo.image_url %>" width="300" height="150" />
    </td>
    <td>
      <a href="<%= recipe_path(recipe.id) %>">View Details</a>
    </td>
  </tr>
  <% end %>
</table>

app/views/recipes/show.html.erb
<h1>Recipe Detail</h1>

<table border='1'>
  <tr>
    <th>Title:</th>
    <td><%= @recipe.title %></td>
  </tr>
  <tr>
    <th>Image:</th>
    <td><img src="<%= @recipe.photo.image_url %>" width="400" height="200" /></td>
  </tr>  
  <tr>
    <th rowspan="2">List of Tags:</th>
  </tr>
  <tr>
    <td>
      <% if @recipe.fields[:tags].present? %>
        <ul>
          <% @recipe.tags.each do |tag| %>
            <li><%= tag.fields[:name] %></li>
          <% end %>
        <ul/>
      <% else %>
        <span>N/A</span>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>Description:</th>
    <td><%= @recipe.description %></td>
  </tr>
  <tr>
    <th>Chef Name:</th>
    <td><%= @recipe.chef.name rescue 'N/A' %></td>
  </tr>
</table>
<br>
<a href="<%= recipes_path %>">Back to All Recipes</a>